# Minimum strongswan.conf for our use.
# Real config lives in ipsec.conf (legacy starter syntax).

charon {
    install_routes = yes
    install_virtual_ip = yes

    # Plugins we explicitly want loaded
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf
    }
}

include strongswan.d/*.conf
