#!/usr/bin/env bash
# Part of proxy-filter localtest — see ./README.md
#
# Starts mitmproxy in WireGuard mode using OUR existing CA, and writes
# a ready-to-import WireGuard client config at ./wg/import.conf.
#
# Strategy:
#   1. Make sure the keys file mitmproxy uses exists (run mitmdump
#      briefly to seed it the very first time; thereafter it's stable).
#   2. Read the keys, compute the server public key with `wg pubkey`,
#      and synthesize a proper WireGuard [Interface]/[Peer] config
#      with Endpoint = 127.0.0.1:51820 (works on this same Mac).
#   3. Launch mitmdump in the background.

set -euo pipefail

cd "$(dirname "$0")"
LOCALTEST_DIR="$(pwd)"
SERVER_DIR="$(cd ../server && pwd)"
CONF_DIR="$LOCALTEST_DIR/mitm-conf"
WG_DIR="$LOCALTEST_DIR/wg"
WG_KEYS="$WG_DIR/wireguard.conf"
WG_IMPORT="$WG_DIR/import.conf"
LOG_FILE="/tmp/proxy-filter-localtest.log"
PID_FILE="/tmp/proxy-filter-localtest.pid"
PROFILE="${LOCALTEST_PROFILE:-sarah}"

echo "============================================="
echo "proxy-filter localtest"
echo "  Profile:       $PROFILE"
echo "  Server dir:    $SERVER_DIR"
echo "  Log file:      $LOG_FILE"
echo "============================================="

# ---- Sanity ----
if [[ ! -f "$SERVER_DIR/ssl/ca.crt" || ! -f "$SERVER_DIR/ssl/ca.key" ]]; then
  echo "ERROR: CA missing. Run: cd ../server/ssl && ./generate-ca.sh" >&2
  exit 1
fi
command -v mitmdump >/dev/null || { echo "ERROR: brew install mitmproxy" >&2; exit 1; }
command -v wg >/dev/null       || { echo "ERROR: brew install wireguard-tools" >&2; exit 1; }
command -v python3 >/dev/null  || { echo "ERROR: python3 required (built-in on macOS)" >&2; exit 1; }

# ---- mitmproxy CA + per-profile dirs ----
mkdir -p "$CONF_DIR" "$WG_DIR"
cat "$SERVER_DIR/ssl/ca.key" "$SERVER_DIR/ssl/ca.crt" > "$CONF_DIR/mitmproxy-ca.pem"
chmod 600 "$CONF_DIR/mitmproxy-ca.pem"
mkdir -p "$SERVER_DIR/profiles/$PROFILE"
touch "$SERVER_DIR/profiles/$PROFILE/blocklist.txt"
touch "$SERVER_DIR/profiles/$PROFILE/allowlist.txt"

# ---- Stop any previous instance ----
if [[ -f "$PID_FILE" ]]; then
  OLD_PID="$(cat "$PID_FILE" 2>/dev/null || echo)"
  [[ -n "$OLD_PID" ]] && kill "$OLD_PID" 2>/dev/null || true
fi
pkill -f "mitmdump.*--mode.*wireguard" 2>/dev/null || true
sleep 1

# ---- Seed the keys file (one-shot) if it doesn't exist yet ----
if [[ ! -s "$WG_KEYS" ]]; then
  echo "First run — generating WireGuard keys..."
  mitmdump --mode "wireguard:$WG_KEYS" --set confdir="$CONF_DIR" \
    -s "$LOCALTEST_DIR/filter_addon.py" > /dev/null 2>&1 &
  SEED_PID=$!
  for _ in $(seq 1 30); do
    [[ -s "$WG_KEYS" ]] && break
    sleep 0.2
  done
  kill "$SEED_PID" 2>/dev/null || true
  pkill -f "mitmdump.*--mode.*wireguard" 2>/dev/null || true
  sleep 1
  if [[ ! -s "$WG_KEYS" ]]; then
    echo "ERROR: mitmdump didn't write keys to $WG_KEYS" >&2
    exit 1
  fi
fi

# ---- Synthesize the WireGuard client config from the keys ----
SERVER_PRIV="$(python3 -c "import json; print(json.load(open('$WG_KEYS'))['server_key'])")"
CLIENT_PRIV="$(python3 -c "import json; print(json.load(open('$WG_KEYS'))['client_key'])")"
SERVER_PUB="$(echo "$SERVER_PRIV" | wg pubkey)"

cat > "$WG_IMPORT" <<EOF
# proxy-filter localtest WireGuard client config.
# Generated by start.sh — re-run start.sh to regenerate.
# Endpoint is 127.0.0.1 because client and server are on the same Mac.

[Interface]
PrivateKey = $CLIENT_PRIV
Address    = 10.0.0.1/32
DNS        = 10.0.0.53
MTU        = 1420

[Peer]
PublicKey  = $SERVER_PUB
AllowedIPs = 0.0.0.0/0
Endpoint   = 127.0.0.1:51820
PersistentKeepalive = 25
EOF

# ---- Start mitmdump for real ----
: > "$LOG_FILE"
LOCALTEST_PROFILE="$PROFILE" \
nohup mitmdump --mode "wireguard:$WG_KEYS" --set confdir="$CONF_DIR" \
  -s "$LOCALTEST_DIR/filter_addon.py" >> "$LOG_FILE" 2>&1 &
echo "$!" > "$PID_FILE"

sleep 2
if ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "ERROR: mitmdump failed to start. Last log:" >&2
  tail -30 "$LOG_FILE" >&2
  exit 1
fi

echo
echo "✓ mitmdump running (pid $(cat "$PID_FILE"))"
echo
echo "Files:"
echo "  WireGuard config:    $WG_IMPORT"
echo "  CA cert (to trust):  $SERVER_DIR/ssl/ca.crt"
echo "  Live log:            tail -f $LOG_FILE"
echo
echo "Next steps:"
echo "  1. Trust the CA (one-time):"
echo "       open '$SERVER_DIR/ssl/ca.crt'"
echo "       Keychain Access → 'Proxy Filter CA' → double-click →"
echo "       expand 'Trust' → 'When using this certificate' → Always Trust → close"
echo
echo "  2. Activate the WireGuard tunnel — pick one:"
echo "       — CLI (already installed, works right now):"
echo "             sudo wg-quick up '$WG_IMPORT'"
echo "             sudo wg-quick down '$WG_IMPORT'    # to turn it off later"
echo "       — GUI (nicer for iterating, optional):"
echo "             Install WireGuard from the Mac App Store"
echo "             (search 'WireGuard'; published by 'WireGuard Development Team')."
echo "             It is NOT in Homebrew Cask — don't 'brew install --cask wireguard'."
echo "             Then: open -a WireGuard '$WG_IMPORT'"
echo
echo "  3. Test:"
echo "       curl https://example.com           → ALLOW (in $LOG_FILE)"
echo "       curl https://777.com               → BLOCKED (default blocklist)"
echo "     Add domains to $PROFILE's blocklist via the dashboard"
echo "     (Proxy → Proxy Profiles → $PROFILE → Settings → Blocked Domains)."
echo "     Filter live-reloads within ~1s, no restart needed."
echo
echo "  4. Stop:  ./stop.sh"
